### ISSUE TITLE
BBCode+: CSS should be appended to head instead of body

### ISSUE THREAD

**Issue by realicraft** [tbgers/tbg-extensions#1]
This can be accomplished by using `document.head.appendChild()` instead of `document.body.appendChild()`. I would make a pull request with that change, but I'm using a phone with poor internet.

**Comment by Gilbert189** [comment]
Implemented in [this commit](https://github.com/tbgers/tbg-extensions/commit/9be5cf3d8b8f22b9f63ed8358eb40d7233736a22).
